apiVersion: ai.sap.com/v1alpha1
kind: Executable
metadata:
  name: video-ai-gpu-worker
spec:
  image: docker.io/nagthgr8/video-ai-gpu-worker:1.0
  resources:
    limits:
      nvidia.com/gpu: 1
      memory: "24Gi"
      cpu: "4"
  ports:
    - containerPort: 8080
  env:
    - name: S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: video-ai-secrets
          key: S3_ENDPOINT
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: video-ai-secrets
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: video-ai-secrets
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_REGION
      value: us-east-1
