apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: video-ai-orchestrator
  namespace: default
  labels:
    ai.sap.com/app-name: video-ai-app
    scenarios.ai.sap.com/id: video-ai-scenario
spec:
  template:
    spec:
      containers:
        - name: job-watcher
          image: docker.io/nagthgr8/video-ai-orchestrator:1.0
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: video-ai-secrets
                  key: S3_ENDPOINT
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: video-ai-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: video-ai-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              value: us-east-1
            - name: GPU_WORKER_URL
              value: http://video-ai-gpu-worker:8080
