apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: video-ai-orchestrator
  annotations:
    scenarios.ai.sap.com/name: "video-ai-orchestration"
    scenarios.ai.sap.com/description: "Video AI orchestration service"
    executables.ai.sap.com/name: "video-ai-orchestrator"
    executables.ai.sap.com/description: "Continuous video job watcher"
  labels:
    ai.sap.com/version: "1.0.0"
    scenarios.ai.sap.com/id: "video-ai-scenario"

spec:
  inputs:
    parameters:
      - name: image
        type: string
        default: docker.io/nagthgr8/video-ai-orchestrator:1.0
        description: Docker image for video AI orchestration

  template:
    apiVersion: serving.kserve.io/v1beta1

    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 1
      labels: |
        {"ai.sap.com/resourcePlan": "basic"}

    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: {{inputs.parameters.image}}
            imagePullPolicy: Always
            command: ["python", "job_watcher.py"]
            resources:
              limits:
                cpu: "2"
                memory: "4Gi"
            env:
              - name: S3_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: S3_ENDPOINT
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: AWS_SECRET_ACCESS_KEY
              - name: AWS_REGION
                value: us-east-1
              - name: GPU_WORKER_URL
                value: http://video-ai-gpu-worker:8080
