apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: video-ai-gpu-worker-v393
  annotations:
    scenarios.ai.sap.com/name: "video-ai-scenario"
    scenarios.ai.sap.com/description: "Video AI GPU worker service"
    executables.ai.sap.com/name: "video-ai-gpu-worker"
    executables.ai.sap.com/description: "GPU worker for video AI processing"
  labels:
    ai.sap.com/version: "1.0.0"
    scenarios.ai.sap.com/id: "video-ai-scenario"

spec:
  inputs:
    parameters:
      - name: image
        type: string
        default: docker.io/ramcna/video-ai-gpu-worker:3.9.3
        description: Docker image for GPU worker

  template:
    apiVersion: serving.kserve.io/v1beta1

    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 1
      labels: |
        {"ai.sap.com/resourcePlan": "infer.m"}

    spec: |
      predictor:
        imagePullSecrets:
          - name: whisper-registry      
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: {{inputs.parameters.image}}
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              limits:
                nvidia.com/gpu: 1
                memory: "25Gi"
                cpu: "7"
            requests:
              nvidia.com/gpu: 1
              memory: "12Gi"
              cpu: "3"
            env:
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: S3_BUCKET
              - name: S3_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: S3_ENDPOINT
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: video-ai-secrets
                    key: AWS_SECRET_ACCESS_KEY
              - name: AWS_REGION
                value: us-east-1
              - name: PYTORCH_CUDA_ALLOC_CONF
                value: "expandable_segments:True"
